In [64]:
import numpy as np
import pandas as pd

## Creating a DataFream

In [65]:
data = {
'Name': ['John', 'Anna', 'Peter', 'Linda'],
'Age': [28, 34, 29, 42],
'City': ['New York', 'Paris', 'Berlin', 'London'],
'Salary': [65000, 70000, 62000, 85000]
}

df = pd.DataFrame(data)

In [66]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [67]:
data_list = [
['John', 28, 'New York', 65000],
['Anna', 34, 'Paris', 70000],
['Peter', 29, 'Berlin', 62000],
['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
columns = ["Name", "Age","City","Salary"]
df2 = pd.DataFrame(data_list, columns =columns)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [68]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

## Selection and Indexing of columns

In [69]:
df2['Name']
df2['City']

0    New York
1       Paris
2      Berlin
3      London
Name: City, dtype: str

In [70]:
df2['Salary']

0    65000
1    70000
2    62000
3    85000
Name: Salary, dtype: int64

In [71]:
df2[["Name", "City"]]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

## Creating a new columns

In [72]:
df2["Designation"] = ["Doctor", "Eng", "Doctor", "Eng"]

In [73]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000         Eng
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000         Eng

## Removing Columns

In [74]:
df2.drop('Designation', axis=1)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [75]:
df2.drop('Age', axis=1)

    Name      City  Salary Designation
0   John  New York   65000      Doctor
1   Anna     Paris   70000         Eng
2  Peter    Berlin   62000      Doctor
3  Linda    London   85000         Eng

In [76]:
df2.drop('Name', axis=1)

   Age      City  Salary Designation
0   28  New York   65000      Doctor
1   34     Paris   70000         Eng
2   29    Berlin   62000      Doctor
3   42    London   85000         Eng

In [77]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000         Eng
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000         Eng

In [78]:
df2.drop('Designation', axis=1)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [79]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000         Eng
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000         Eng

In [80]:
df2.drop('Designation', axis=1, inplace= True)

In [81]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

Removing Row

In [82]:
df2.drop(0, axis=0)

    Name  Age    City  Salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

In [83]:
df2.drop(3, axis=0)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000

In [84]:
data1 = {
    
    'Calories' : [420,380,390],
    'Duration' : [50,40,45]
}

In [85]:
df2 = pd.DataFrame(data1,index=('day1', 'day2', 'day3'))
df2

      Calories  Duration
day1       420        50
day2       380        40
day3       390        45

In [86]:
df2

      Calories  Duration
day1       420        50
day2       380        40
day3       390        45

In [87]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [94]:
data2 = {
    'Name': ['Surya', 'Rohan', 'Rohit', 'Kali'],
    'Age' : [20,22,19,20],
    'College' : ['ABES', 'ABES', 'ABES', 'ABES']
}
df3 = pd.DataFrame(data2)
df3

    Name  Age College
0  Surya   20    ABES
1  Rohan   22    ABES
2  Rohit   19    ABES
3   Kali   20    ABES

In [96]:
df5 = pd.read_csv('bollywood.csv')

In [95]:
df.head()

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

## Data Read

In [101]:
df5

                                     movie              lead
0                 Uri: The Surgical Strike     Vicky Kaushal
1                            Battalion 609       Vicky Ahuja
2     The Accidental Prime Minister (film)       Anupam Kher
3                          Why Cheat India     Emraan Hashmi
4                          Evening Shadows  Mona Ambegaonkar
...                                    ...               ...
1495                Hum Tumhare Hain Sanam    Shah Rukh Khan
1496                   Aankhen (2002 film)  Amitabh Bachchan
1497                       Saathiya (film)      Vivek Oberoi
1498                        Company (film)        Ajay Devgn
1499                  Awara Paagal Deewana      Akshay Kumar

[1500 rows x 2 columns]

In [102]:
df5.head()

                                  movie              lead
0              Uri: The Surgical Strike     Vicky Kaushal
1                         Battalion 609       Vicky Ahuja
2  The Accidental Prime Minister (film)       Anupam Kher
3                       Why Cheat India     Emraan Hashmi
4                       Evening Shadows  Mona Ambegaonkar

In [103]:
df5.tail()

                       movie              lead
1495  Hum Tumhare Hain Sanam    Shah Rukh Khan
1496     Aankhen (2002 film)  Amitabh Bachchan
1497         Saathiya (film)      Vivek Oberoi
1498          Company (film)        Ajay Devgn
1499    Awara Paagal Deewana      Akshay Kumar

In [104]:
df5.sample(6)

                      movie              lead
1158  Corporate (2006 film)      Bipasha Basu
648      Super Model (film)      Ashmit Patel
1496    Aankhen (2002 film)  Amitabh Bachchan
987               Halla Bol        Ajay Devgn
912                   Pankh      Bipasha Basu
811     Miley Naa Miley Hum     Chirag Paswan

In [109]:
df5.sample(4)

                      movie            lead
806   Love Breakups Zindagi      Zayed Khan
1281      Mr Prime Minister       Dev Anand
644                  Maazii  Sumit Nijhawan
943    New York (2009 film)    John Abraham

In [118]:
df6 = pd.read_csv('Book1.csv')

In [119]:
df6

          Employee_ID,Name,Sector,Company,Salary
0                1,Aarav Sharma,IT,Infosys,58000
1          2,Priya Verma,Banking,HDFC Bank,72000
2                     3,Rahul Singh,IT,TCS,65000
3            4,Neha Gupta,Finance,Deloitte,81000
4   5,Aman Yadav,Manufacturing,Tata Motors,55000
..                                           ...
94                   95,Suraj Singh,IT,TCS,76000
95        96,Nidhi Verma,E-Commerce,Amazon,99000
96  97,Anurag Yadav,Automobile,Tata Motors,65000
97               98,Roshni Jain,Finance,EY,84000
98             99,Vikas Kumar,IT,Accenture,80000

[99 rows x 1 columns]

In [120]:
df6.head()

         Employee_ID,Name,Sector,Company,Salary
0               1,Aarav Sharma,IT,Infosys,58000
1         2,Priya Verma,Banking,HDFC Bank,72000
2                    3,Rahul Singh,IT,TCS,65000
3           4,Neha Gupta,Finance,Deloitte,81000
4  5,Aman Yadav,Manufacturing,Tata Motors,55000

### DataFreams

In [124]:
Data = {
    'S.No' : [1,2,3,4],
    'Name' : ['Tom', 'Lee', 'Steven','Ram'],
    'Age': [28,34,22,12],
    'City' : ['Japan', 'HongKong', 'Delhi', 'pune'],
    'Salary' : [200000,40000,234003,233002]
}
df9 = pd.DataFrame(Data)

In [125]:
df9

   S.No    Name  Age      City  Salary
0     1     Tom   28     Japan  200000
1     2     Lee   34  HongKong   40000
2     3  Steven   22     Delhi  234003
3     4     Ram   12      pune  233002

In [122]:
df9

   S.No    Name  Age      City  Salary
0     1     Tom   28     Japan  200000
1     2     Lee   34  HongKong   43332
2     3  Steven   22     Delhi   23433
3     4     Ram   12      pune   23432