In [9]:
import numpy as np
import pandas as pd

## Finding Missing Data

In [14]:
data = {
'A': [1, 2, np.nan, 4, 5],
'B': [np.nan, 2, 3, 4, 5],
'C': [1, 2, 3, np.nan, np.nan],
'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame (data)

In [15]:
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [16]:
df.isna().sum()

A    1
B    1
C    2
D    3
dtype: int64

In [17]:
df.isna().any()

A    True
B    True
C    True
D    True
dtype: bool

## Removing Missing Data

In [18]:
df.dropna()

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [19]:
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [20]:
df.dropna(thresh=3)

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
4  5.0  5.0  NaN  5.0

In [21]:
df.dropna(thresh=4)

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [22]:
df.dropna(thresh=2)

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [23]:
df.dropna(thresh=5)

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [24]:
df.dropna(thresh=6)

Empty DataFrame
Columns: [A, B, C, D]
Index: []

## Filling the missing Data

In [25]:
df.fillna(0)

     A    B    C    D
0  1.0  0.0  1.0  1.0
1  2.0  2.0  2.0  0.0
2  0.0  3.0  3.0  0.0
3  4.0  4.0  0.0  0.0
4  5.0  5.0  0.0  5.0

In [26]:
df.fillna(5)

     A    B    C    D
0  1.0  5.0  1.0  1.0
1  2.0  2.0  2.0  5.0
2  5.0  3.0  3.0  5.0
3  4.0  4.0  5.0  5.0
4  5.0  5.0  5.0  5.0

In [27]:
values = {'A':0, 'B':100, 'C':300, 'D':400}
df.fillna(value=values)

     A      B      C      D
0  1.0  100.0    1.0    1.0
1  2.0    2.0    2.0  400.0
2  0.0    3.0    3.0  400.0
3  4.0    4.0  300.0  400.0
4  5.0    5.0  300.0    5.0

In [28]:
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [29]:
df.fillna(df.mean())

     A    B    C    D
0  1.0  3.5  1.0  1.0
1  2.0  2.0  2.0  3.0
2  3.0  3.0  3.0  3.0
3  4.0  4.0  2.0  3.0
4  5.0  5.0  2.0  5.0